<a href="https://colab.research.google.com/drive/1_9b6XAhXJL98kHkufn7PkKyK3q-9BYZv?usp=sharing" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 01. PyTorch Tensor Fundamentals Exercises [20 points]

### 1. [2 points] Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. [2 points] Create a random tensor with shape `(8, 8)`. 


In [ ]:
# Import torch

# Create random tensor


### 3. [2 points] Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 8)` (hint: you may have to transpose the second tensor). 

In [ ]:
# Create another random tensor

# Perform matrix multiplication


### 4. [2 points] Set the random seed to `0` and do 2 & 3 over again. 

The output should be:
```
(tensor([[2.0579],
         [1.4392],
         [2.9189],
         [1.9295],
         [1.7499],
         [1.5325],
         [2.7487],
         [2.2421]]),
 torch.Size([8, 1]))
```

In [ ]:
# Set manual seed

# Create two random tensors

# Matrix multiply tensors


### 5. [2 points] Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one) 
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU



### 6. [2 points] Create two random tensors of shape `(3, 2)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019],
         [0.2598, 0.3666],
         [0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681],
         [0.6738, 0.3315],
         [0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed

# Check for access to GPU

# Create two random tensors on GPU



### 7. [2 points] Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.1896, 0.1527, 0.2490],
         [0.1851, 0.2966, 0.4101],
         [0.3310, 0.2715, 0.4402]], device='cuda:0'),
 torch.Size([3, 3]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. [2 points] Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. [2 points] Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max

# Find arg min



### 10. [2 points] Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `8` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141,
           0.5785, 0.1218]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141, 0.5785,
        0.1218]) torch.Size([10])
```

In [ ]:
# Set seed

# Create random tensor

# Remove single dimensions

# Print out tensors
